### ISSUE TITLE
pubmed-pmc-large version seems wrong

### ISSUE THREAD

**Issue by qiuhaolu** [justinphan3110/SciFive#10]
Thanks for sharing the models.
I found that the pubmed-pmc-large version (https://huggingface.co/razent/SciFive-large-Pubmed_PMC/tree/main) seems wrong as the fine-tuning results on MEDNLI are drastically worse than T5-large (acc 0.67+ vs 0.82+). However, the pubmed-large version gives good results.

Could you confirm this version?

**Comment by justinphan3110** [comment]
Hi @qiuhaolu , can you share the notebook to reproduce these fail results?

**Comment by qiuhaolu** [comment]
Thanks @justinphan3110. The model should be right.
