### ISSUE TITLE
fine-tuned models

### ISSUE THREAD

**Issue by kletinic** [justinphan3110/SciFive#11]
Hi Justin, I needed QA model, which need to be fine tuned, but wantet to ask if NER models already fine-tuned are available? Thanks

**Comment by Esther-Id** [comment]
Hii kletinic, I seem to require the same thing you asked for earlier; which did you get to use/or may be created?  ,thanks

**Comment by justinphan3110** [comment]
[finetunning_biot5x_blurb.ipynb](https://github.com/justinphan3110/SciFive/blob/main/biot5x/examples/finetunning_biot5x_blurb.ipynb)
you can reproduce the result from the example file above
