### ISSUE TITLE
SciFive pre-training not using the init checkpoint

### ISSUE THREAD

**Issue by JorgeGabin** [justinphan3110/SciFive#13]
I am a PhD student trying to use your model for a research project.

Looking at the pre-training notebooks, it seems you do not use an init checkpoint to continue the training of the t5 model. Is this because you already have checkpoints in your model directory or because you train t5 from zero instead of using an already pre-trained T5 model?

**Comment by JorgeGabin** [comment]
@justinphan3110, thanks for the fast answer.

I am also having some overtraining issues in the pre-training phase. After I pre-train the T5-base model for extra 300k steps with a batch size of 32, executing the standard question-answering task produces much worse results than the T5-base model. Checking the outputs generated by the model, I can see that the model tends to generate answers which contain pre-train special tokens (e.g. "<extra_id_0>"). Did you face any similar issues?

**Comment by justinphan3110** [comment]
@JorgeGabin can you share the code that can reproduce that. Make sure you have the prefix during finetunning and inference time

**Comment by JorgeGabin** [comment]
@justinphan3110 Sorry for the late reply. We found out that this only happens when using the span corruption preprocessor (used in the T5 paper) and not the unsupervised one you use in the script. Thank you!
