### ISSUE TITLE
Vocab is not accessible, it is in gs://t5-data

### ISSUE THREAD

**Issue by cnut1648** [justinphan3110/SciFive#14]
Hello, first of all, I want to say nice work! 

When I want to reproduce [your results on chemprot](https://github.com/justinphan3110/SciFive/blob/main/finetune/re/chemprot_1.ipynb), I notice the following auth issue in the code
```
model.finetune(
    mixture_or_task_name="re_all",
    pretrained_model_dir=PRETRAINED_DIR,
    finetune_steps=FINETUNE_STEPS
)
```
```
2022-11-30 14:46:16.639835: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
```
Turns out that this is caused by not being able to find vocab which is in `'gs://t5-data/vocabs/cc_all.32000/sentencepiece.model'`. But currently only `gs://scifive` is accessible. 

Could you please release the vocab or share with us how exactly did you obtain the sentencepiece vocab so that we can reproduce the results? Thank you!

**Comment by justinphan3110** [comment]
Hi @cnut1648, Thank you for your interest in our work. There is an error in the Chemprot evaluation that affected our model's results. We already removed it on [PaperWithCode-Chemprot](https://paperswithcode.com/sota/relation-extraction-on-chemprot).

**Comment by justinphan3110** [comment]
Hey @cnut1648 , Sorry for the late response. On the Chemprot task, we found out that we used the same eval approach as in scibert. Therefore, we found out that the chemprot result reported in the paper is not comparable to other recent works. 

The new results for Scifive on chemprot should be: `~78`

Let me know if you still want the code to reproduce this result

**Comment by justinphan3110** [comment]
@cnut1648  I have just updated the script to use the similar chemprot dataset as the [BLURB Leaderboard](https://microsoft.github.io/BLURB/leaderboard.html). You can access it [here](https://github.com/justinphan3110/SciFive/blob/main/finetune/re/chemprot_scifive_blurb_colab.ipynb). Let me know if you still have any question

**Comment by cnut1648** [comment]
Hi @justinphan3110 thanks! I can reproduce the results now! Great work!
