### ISSUE TITLE
BioT5X for NLI

### ISSUE THREAD

**Issue by mstrise** [justinphan3110/SciFive#16]
Hi! Very interesting work! 
Could you also provide a script for finetuning an NLI task with BIOT5X and describe the data format of MedNLI required for BiOT5X and how it should be exactly preprocessed?
Thanks!

**Comment by justinphan3110** [comment]
@mstrise , thanks for interesting in our work.

You can processed the NLI data as:
```
input: sent1:{sent1} sent2:{sent2}
```
There are examples [here](https://github.com/vietai/ViPubmed/tree/main/data/vi_mednli) from another project
