### ISSUE TITLE
The link for finetune dataset has no data

### ISSUE THREAD

**Issue by Dotkat-dotcome** [justinphan3110/SciFive#17]
Hi, thank you for sharing the code.

Is it possible to share the pre-procossed finetune datasets as well?
On the google cloud link, there is no dataset available.

**Comment by justinphan3110** [comment]
Hi @Dotkat-dotcome , please try the examples here: [finetunning_biot5x_blurb](https://github.com/justinphan3110/SciFive/blob/main/biot5x/examples/finetunning_biot5x_blurb.ipynb)

**Comment by Dotkat-dotcome** [comment]
Hi, thanks!
