### ISSUE TITLE
HOC dataset for SCIFIVE

### ISSUE THREAD

**Issue by zoeyhl** [justinphan3110/SciFive#19]
Hi, I noticed that there are two versions of hoc dataset, one is originally sentence-level, and the other is modified by BLURB dataset to abstract-level. Which hoc dataset does SCIFIVE used for fine-tuning? I think it's sentence-level one because the input-length is 256

**Comment by justinphan3110** [comment]
You can take a look to reproduce the result here [finetunning_biot5x_blurb.ipynb](https://github.com/justinphan3110/SciFive/blob/main/biot5x/examples/finetunning_biot5x_blurb.ipynb)

**Comment by zoeyhl** [comment]
Thank you for your reply! It only mentioned using micro-f1 as metrics, but in the paper, I saw also precision and recall were also used. How are precision and recall being calculated? Are they average by "micro" "macro" or "samples"? thank you!
