### ISSUE TITLE
Need Config file for tensorflow checkpoint to Pytorch .bin model conversion (SciFive)

### ISSUE THREAD

**Issue by Mihir3009** [justinphan3110/SciFive#4]
Hi there, 

we want to convert your tensorflow model to pytorch model. We need the config file to do this, however we did not find the config file from this repo, https://console.cloud.google.com/storage/browser/scifive/models?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

could you please share the config file also?

**Comment by justinphan3110** [comment]
Hi, I have just updated. they are available at https://console.cloud.google.com/storage/browser/scifive/config?project=algebraic-creek-280813&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false. 
thank you
