### ISSUE TITLE
About the question_answer?

### ISSUE THREAD

**Issue by ZYuliang** [justinphan3110/SciFive#5]
How can I test the model in the QA task? Just input the text like " How many teeth do humans have?"  or if i need to add the prefix,like "QA: How many teeth do humans have?"

**Comment by MHDBST** [comment]
I found these prefixes in the examples provided in the [GitHub](https://github.com/justinphan3110/SciFive/tree/main/finetune/qa):
`bioasq4b: ... `
`bioasq5b: ... `

**Comment by ZYuliang** [comment]
It doesn't work. However, I find the input [data format](https://console.cloud.google.com/storage/browser/scifive) of the QA task for the t5 model, for example, "question*: .... context*: .... ".

**Comment by MHDBST** [comment]
Did you use the fine tuned model (SciFive) with T5 prefixes? Was it better than T5 itself?

**Comment by ZYuliang** [comment]
The [paper](https://arxiv.org/abs/2106.03598) shows that both have similar results. And the model(SciFive) is a trained t5 model.
