### ISSUE TITLE
Weights for MedNLI

### ISSUE THREAD

**Issue by griff4692** [justinphan3110/SciFive#7]
Is it possible to share the fine-tuned MedNLI classifier with a simple code snippet for how to perform inference given a text and premise pair?  I saw the notebook for fine-tuning but was wondering if the output could be open sourced.  many thanks

**Comment by justinphan3110** [comment]
Hi @griff4692 , you can re finetuned the weights using the mesh tensorflow scripts here https://github.com/justinphan3110/SciFive/blob/main/finetune/nli/mednli_1.ipynb
