### ISSUE TITLE
Performing relation extraction

### ISSUE THREAD

**Issue by ChrisPaneque** [justinphan3110/SciFive#8]
Hi, is there any way to perform relation extraction from new text using any of your models in Huggingface?

**Comment by justinphan3110** [comment]
Hi you can follow the code to [finetune chemprot RE](https://github.com/justinphan3110/SciFive/blob/main/finetune/re/chemprot_1.ipynb) and change with your train data

**Comment by ChrisPaneque** [comment]
Great, thanks a lot!!

**Comment by kletinic** [comment]
Hi Justin, 

I run a startup called DocOne. I wanted to ask you about SciFive models. Can you please confirm that you haven’t released fine-tuned versions?

I need a fine-tuned QA model. If it’s not possible for you to release Sci-Five-large QA, please let me know what code and datasets to use. I just want to make sure I set up fine tuning right. 

(1) I have this link to fine-tuning data sets: https://console.cloud.google.com/storage/browser/scifive/finetune;tab=objects?prefix=&forceOnObjectsSortingFiltering=false <https://console.cloud.google.com/storage/browser/scifive/finetune;tab=objects?prefix=&forceOnObjectsSortingFiltering=false>

Please tell me exactly which ones we should use. There is bioasq8a and I’m not sure if you used it.

(2) I have this link to fine-tuning code: https://github.com/justinphan3110/SciFive/tree/main/finetune/qa <https://github.com/justinphan3110/SciFive/tree/main/finetune/qa>

Is that the correct code and do we have to use all three codes to run on these 3 bioasq datasets?


Thanks a lot!

Kresimir




On 11 Apr 2022, at 03:10, Long Phan ***@***.***> wrote:


Closed #8 <https://github.com/justinphan3110/SciFive/issues/8>.

**Comment by kletinic** [comment]
Justin, 

As a follow up, I found also this link that has numerous resources and I got a little lost.

I would greatly appreciate if you could let me know exactly which QA datasets I should use for fine tuning.  Please provide links - thanks a lot!

Let me know if you’re interested in startups. 

On 27 Apr 2022, at 12:02, Kresimir Letinic ***@***.***> wrote:

Hi Justin, 

I run a startup called DocOne. I wanted to ask you about SciFive models. Can you please confirm that you haven’t released fine-tuned versions?

I need a fine-tuned QA model. If it’s not possible for you to release Sci-Five-large QA, please let me know what code and datasets to use. I just want to make sure I set up fine tuning right. 

(1) I have this link to fine-tuning data sets: https://console.cloud.google.com/storage/browser/scifive/finetune;tab=objects?prefix=&forceOnObjectsSortingFiltering=false <https://console.cloud.google.com/storage/browser/scifive/finetune;tab=objects?prefix=&forceOnObjectsSortingFiltering=false>

Please tell me exactly which ones we should use. There is bioasq8a and I’m not sure if you used it.

(2) I have this link to fine-tuning code: https://github.com/justinphan3110/SciFive/tree/main/finetune/qa <https://github.com/justinphan3110/SciFive/tree/main/finetune/qa>

Is that the correct code and do we have to use all three codes to run on these 3 bioasq datasets?


Thanks a lot!

Kresimir




On 11 Apr 2022, at 03:10, Long Phan ***@***.*** ***@***.***>> wrote:


Closed #8 <https://github.com/justinphan3110/SciFive/issues/8>.
